"""Build c4_full.js and protobuf/c4_full.pb.gz from the base graph plus
steady_states.txt.

    python build_graph.py            # regenerate both artifacts
    python build_graph.py --check    # fail if the committed artifacts are stale
    python build_graph.py --report   # print node counts as JSON, write nothing

graph/base_c4_full.js is the canonical graph as generated by SwapTube and is
never edited here. Applying a diagram turns its node into a leaf, which makes
that node's private subtree unreachable; those nodes are then dropped.

Output is byte-reproducible, so --check is a meaningful staleness test and an
empty steady_states.txt reproduces the published graph exactly.

Needs the protobuf package for the .pb.gz (pip install protobuf); pass
--skip-protobuf to build only the JavaScript.
"""
from __future__ import annotations

import argparse
import gzip
import io
import json
import re
import sys
from pathlib import Path

import verify_steady_states as vss

HERE = Path(__file__).resolve().parent
BASE_GRAPH = HERE / "graph" / "base_c4_full.js"
ENTRIES = HERE / "steady_states.txt"
OUT_JS = HERE / "c4_full.js"
OUT_PB = HERE / "protobuf" / "c4_full.pb.gz"

# character -> 4-bit code, matching protobuf/pack_protobuf.py
SS_CODES = {" ": 0, "1": 1, "2": 2, "|": 3, "!": 4, "-": 5, "@": 6, "+": 7, "=": 8}


def load_base():
    """Load the base graph, preserving float literals exactly.

    SwapTube's C++ writer does not always print a double with the digits
    Python's repr() would choose for the same value. Keeping the original text
    means a rebuild only ever shows real changes instead of rewriting all 2 MB.
    """
    text = BASE_GRAPH.read_text(encoding="utf-8")
    match = re.fullmatch(r"\s*var\s+dataset\s*=\s*(\{.*?\})\s*;?\s*", text, re.S)
    if not match:
        raise ValueError(f"{BASE_GRAPH} is not a recognizable WeakC4 dataset")
    literals = []

    def keep(literal):
        literals.append(literal)
        return f"~~F{len(literals) - 1}~~"

    return json.loads(match.group(1), parse_float=keep), literals


def board_key(position):
    return tuple(tuple(row) for row in vss.board_from_position(position))


def reachable_from(nodes, root):
    seen, stack = set(), [root]
    while stack:
        node_hash = stack.pop()
        if node_hash in seen:
            continue
        seen.add(node_hash)
        neighbors = nodes[node_hash]["neighbors"]
        if neighbors is not None:
            stack.extend(neighbors)
    return seen


def apply_entries(dataset, entries):
    """Apply every entry, then prune unreachable nodes."""
    nodes = dataset["nodes_to_use"]
    root = dataset["root_node_hash"]

    by_board = {}
    for node_hash, node in nodes.items():
        key = board_key(node["rep"])
        if key in by_board:
            raise AssertionError(
                f"base graph has duplicate boards: {by_board[key]} and {node_hash}"
            )
        by_board[key] = node_hash

    nodes_before = len(nodes)
    applied, notes = [], []
    for position, diagram, _line in entries:
        node_hash = by_board.get(board_key(position))
        if node_hash is None:
            notes.append({"position": position, "note": "not present in the base graph"})
            continue
        if node_hash == root:
            raise AssertionError("an entry may not replace the graph root")
        node = nodes[node_hash]
        if node["neighbors"] is None:
            notes.append({"position": position, "note": "already a diagram leaf upstream"})
        node["data"]["ss"] = vss.ss_from_diagram(diagram)
        node["neighbors"] = None
        applied.append((position, node_hash))

    keep = reachable_from(nodes, root)
    for node_hash in list(nodes):
        if node_hash not in keep:
            del nodes[node_hash]

    effective = 0
    for position, node_hash in applied:
        if node_hash in nodes:
            effective += 1
        else:
            notes.append({"position": position,
                          "note": "subsumed: another entry already removed this node"})

    for node_hash, node in nodes.items():
        if node["neighbors"] is None:
            continue
        bad = [n for n in node["neighbors"] if n not in nodes]
        if bad:
            raise AssertionError(f"dangling edges at {node_hash}: {bad[:5]}")

    return dataset, {
        "entries": len(entries),
        "applied": len(applied),
        "effective": effective,
        "nodes_before": nodes_before,
        "nodes_after": len(nodes),
        "nodes_removed": nodes_before - len(nodes),
        "notes": notes,
    }


def render_js(dataset, literals):
    out = "var dataset = " + json.dumps(
        dataset, ensure_ascii=False, separators=(",", ":")
    )
    return re.sub(r'"~~F(\d+)~~"', lambda m: literals[int(m.group(1))], out)


def render_protobuf(dataset):
    sys.path.insert(0, str(HERE / "protobuf"))
    try:
        import c4_graph_pb2
    except ImportError as exc:  # pragma: no cover - environment dependent
        raise SystemExit("pip install protobuf, or pass --skip-protobuf") from exc

    nodes = dataset["nodes_to_use"]
    hash_to_id = {node_hash: index for index, node_hash in enumerate(nodes)}

    ds = c4_graph_pb2.Dataset()
    ds.root_node_id = hash_to_id[dataset["root_node_hash"]]
    for node_hash, node_json in nodes.items():
        node = ds.nodes.add()
        node.id = hash_to_id[node_hash]
        digits = [int(ch) for ch in node_json["rep"]]
        node.rep = bytes(
            (digits[i] << 3) | (digits[i + 1] if i + 1 < len(digits) else 0)
            for i in range(0, len(digits), 2)
        )
        if node_json["neighbors"] is not None:
            node.neighbor_data.neighbor_ids.extend(
                hash_to_id[target] for target in node_json["neighbors"]
            )
        else:
            flat = [SS_CODES[chr(v)] for row in node_json["data"]["ss"] for v in row]
            node.flat_ss = bytes(
                (flat[i] << 4) | (flat[i + 1] if i + 1 < len(flat) else 0)
                for i in range(0, len(flat), 2)
            )

    buffer = io.BytesIO()
    # mtime=0 keeps the gzip container byte-reproducible across runs.
    with gzip.GzipFile(fileobj=buffer, mode="wb", mtime=0) as handle:
        handle.write(ds.SerializeToString(deterministic=True))
    return buffer.getvalue()


def build(skip_protobuf=False, entries_path=ENTRIES):
    dataset, literals = load_base()
    entries_path = Path(entries_path)
    text = entries_path.read_text(encoding="utf-8") if entries_path.exists() else ""
    entries = vss.parse_entries(text, source=entries_path.name)
    dataset, report = apply_entries(dataset, entries)
    artifacts = {OUT_JS: render_js(dataset, literals).encode("utf-8")}
    if not skip_protobuf:
        artifacts[OUT_PB] = render_protobuf(dataset)
    return artifacts, report


def markdown(report):
    out = ["### Graph size\n"]
    if "nodes_before_pr" in report:
        delta = report["nodes_after"] - report["nodes_before_pr"]
        out.append(f"**{report['nodes_before_pr']:,} -> {report['nodes_after']:,} nodes "
                   f"({delta:+,} from this pull request).**\n")
    else:
        out.append(f"**{report['nodes_after']:,} nodes** "
                   f"({report['nodes_removed']:,} removed from the base graph).\n")
    if report["effective"] < report["entries"]:
        out.append(f"{report['effective']} of {report['entries']} contributed diagrams "
                   "are effective; the rest sit inside a subtree another diagram "
                   "already removed.\n")
    if report.get("stale"):
        out.append("Committed artifacts are stale: " + ", ".join(report["stale"]) + "\n")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="compare against the committed artifacts, write nothing")
    parser.add_argument("--report", action="store_true",
                        help="print counts only, write nothing")
    parser.add_argument("--skip-protobuf", action="store_true", help="build only c4_full.js")
    parser.add_argument("--entries", type=Path, default=ENTRIES,
                        help="entry file to apply (default: steady_states.txt)")
    parser.add_argument("--baseline", type=Path, default=None,
                        help="also report the node count this entry file would give")
    parser.add_argument("--markdown", action="store_true",
                        help="print a short report instead of JSON")
    args = parser.parse_args()

    artifacts, report = build(
        skip_protobuf=args.skip_protobuf or args.report, entries_path=args.entries
    )
    if args.baseline is not None:
        _, before = build(skip_protobuf=True, entries_path=args.baseline)
        report["nodes_before_pr"] = before["nodes_after"]

    if args.report:
        report["status"] = "OK"
    elif args.check:
        report["stale"] = [
            path.name for path, content in artifacts.items()
            if not path.exists() or path.read_bytes() != content
        ]
        report["status"] = "OK" if not report["stale"] else "STALE"
    else:
        for path, content in artifacts.items():
            path.write_bytes(content)
        report["written"] = sorted(path.name for path in artifacts)
        report["status"] = "OK"

    print(markdown(report) if args.markdown else json.dumps(report, indent=2, sort_keys=True))
    sys.exit(1 if report["status"] != "OK" else 0)


if __name__ == "__main__":
    main()
